# Generated by Django 3.1.4 on 2020-12-03 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
