# Generated by Django 3.1.4 on 2020-12-04 02:35

import autoslug.fields
import cards.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_auto_20201204_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from=cards.models.generate_card_slug, slugify=cards.models.hierarchical_slugify, unique_with=('deck', 'name')),
        ),
    ]
